### ISSUE TITLE
Add a way to show an original exception in `--verbose` mode.

### ISSUE THREAD

**Issue by alloy** [CocoaPods/CLAide#31]
I’m thinking an attribute like `CLAide::InformativeError#wraps_exception`. When the user specifies the `--verbose` flag, the informative error would include the wrapped error message in its output and possibly show the wrapped backtrace instead of the Informative one.

Thoughts?

**Comment by segiddins** [comment]
FWIW, as of (it looks like) Ruby 2.2, there is an `Exception#cause` which does just this, but automatically!
