### ISSUE TITLE
Remove ZSH completion code

### ISSUE THREAD

**Issue by alloy** [CocoaPods/CLAide#43]
It’s not used by all users or even developers that work on CLAide, so it’s quality cannot be guaranteed.

In addition it appears that it doesn’t fully work well, @AliSoftware can you comment on that?

All in all, it’s bloat and as such should be moved out of this library, possibly into a plugin, which could just be a CocoaPods plugin for now.

**Comment by segiddins** [comment]
@alloy should be accomplished by https://github.com/CocoaPods/claide-completion, which I will release as soon as you give me a :+1:

**Comment by alloy** [comment]
Hahaha, that readme is excellent, do it :+1:

**Comment by segiddins** [comment]
:heart:
