### ISSUE TITLE
Open source plugin system

### ISSUE THREAD

**Issue by jcampbell05** [CocoaPods/CLAide#56]
I recently copy and pasted the plugin system you use into Fastlane, it would be awesome if you could extract that into a separate library. :)

**Comment by alloy** [comment]
I’d prefer to wait and see if any other tool, e.g. Fast lane, will actually use it before extracting.

/cc @krausefx

**Comment by segiddins** [comment]
You can already just depend on CLAide and only use it for the plugins...

**Comment by segiddins** [comment]
Closing because I stand behind the idea that CLAide itself is already a nice plugin system :)
