### ISSUE TITLE
Method missing: full_require_paths on macOS system Ruby

### ISSUE THREAD

**Issue by orta** [CocoaPods/CLAide#73]
So, this is the stack trace. Specifically when calling `danger`, no `bundle exec`.

``` 
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1896:in `method_missing': undefined method `full_require_paths' for #<Gem::Specification:0x3fc3d501ba48 claide-plugins-0.9.0> (NoMethodError)
    from /Users/Samantha/.gem/ruby/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:59:in `block (2 levels) in plugins_involved_in_exception'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:58:in `each'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:58:in `any?'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:58:in `block in plugins_involved_in_exception'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:57:in `select'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:57:in `plugins_involved_in_exception'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:415:in `report_error'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:396:in `handle_exception'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:337:in `rescue in run'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:325:in `run'
    from /Users/Samantha/.gem/ruby/2.0.0/gems/danger-0.10.1/bin/danger:5:in `<top (required)>'
    from /Users/Samantha/.gem/ruby/2.0.0/bin/danger:23:in `load'
    from /Users/Samantha/.gem/ruby/2.0.0/bin/danger:23:in `<main>'
```

`$ gem -v` = `2.0.14.1`

It looks like `full_require_paths` was added in Rubygems 2.2 - which isn't installed by default http://blog.rubygems.org/2013/12/26/2.2.0-released.html

https://github.com/CocoaPods/CLAide/blob/master/lib/claide/command/plugin_manager.rb#L59

This only happens when a plugin crashes, which is why we've probably not seen it in CocoaPods yet, probably cause there's real software engineering going on over there 💃 

/cc @samdmarshall

**Comment by segiddins** [comment]
... and bundler monkey-patches it in. I can fix this

**Comment by mokagio** [comment]
@segiddins @orta any plans to release this fix on CLAide and then update the Danger requirement? We've just bumped into this very same issue. Happy to help if I can, although it sounds just like a mundane release step.

Thanks ❤️

**Comment by orta** [comment]
I thought this would have come out with one of the CocoaPods beta releases? @DanToml did you notice this ever coming up? Does it require a change to the CHANGELOG to trigger it being noticed?

**Comment by DanToml** [comment]
@orta yeah during super release you only see the changelog, and the tests all pass on my machine & CI so assumed it was good

**Comment by wilrnh** [comment]
ps. to update rubygems:

`gem update --system`

**Comment by DanToml** [comment]
@orta I can do a release with a fix for this whenever tho

**Comment by orta** [comment]
Sure thing, I'm not very free this evening, but I can make a PR adding the changelog in anticipation of a release ( or you're welcome to beat me to it )

**Comment by samdmarshall** [comment]
@wilrnh that doesn't work on 10.11

```
$ gem update --system
Updating rubygems-update
Fetching: rubygems-update-2.6.6.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.
```

**Comment by wilrnh** [comment]
you need sudo in that case:

`sudo gem update --system`

**Comment by samdmarshall** [comment]
@wilrnh That is defeating the point of this issue, as it should work out of the box with a default RubyGems installation on OS X.

**Comment by wilrnh** [comment]
Def I didn't mean it as fix, just a possible workaround in case you're between a rock and a hard place.

**Comment by orta** [comment]
Added the CHANGELOG - https://github.com/CocoaPods/CLAide/pull/75
