### ISSUE TITLE
What should I do to make a CLAide command visible to shell?

### ISSUE THREAD

**Issue by luqyluqe** [CocoaPods/CLAide#81]
Just like `pod install`.

**Comment by luqyluqe** [comment]
Just like `pod install`.

**Comment by segiddins** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - where people can help out with questions like this. We try to keep the CLAide issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
