### ISSUE TITLE
CLAide incompatible with RubyGems-3.3.0+

### ISSUE THREAD

**Issue by mikehardy** [CocoaPods/CLAide#98]
This was originally logged in Cocoapods main issue list and in the rubygems list (where some great analysis took place, including a reference to the actual bisected commit that caused it)

Logging it here because the actual problem appears to be CLAide here using internals from RubyGems that were unsafe to touch, so an internal refactor of RubyGems for performance triggered a problem here, which transitively breaks cocoapods in combo with ruby-gems-3.3.x

A workaround for affected cocoapods users was posted on the cocoapods issue so users won't get stuck, but it *seems* to me (could be wrong) that the rubygems change was valid + desired from their perspective and the goal is to fix up CLAide here so it functions with new rubygems versions

That's the context. All technical details referenced out from one comment here: https://github.com/CocoaPods/CocoaPods/issues/11134#issuecomment-1006573500

**Comment by mikehardy** [comment]
Cross-linking with upstream issue comment that has the commit reference that CLAide should be able to tolerate:

https://github.com/rubygems/rubygems/issues/5235#issuecomment-1002519760

Option 3 from that comment (fix CLAide) appears to be the preference

**Comment by deivid-rodriguez** [comment]
I sent a fix for this: #99.

**Comment by deivid-rodriguez** [comment]
However this repositories CI seems to run on old `travis-ci.org` which was shutdown. So I guess we need to add a Github Actions configuration to make sure this doesn't break anything. I'll add that now.

**Comment by deivid-rodriguez** [comment]
To try the fix, you can clone this repository, and run `rake install` from it, and that should install the patched version of `CLAide` to your system, that should work fine with rubygems 3.3.x.

**Comment by mikehardy** [comment]
@segiddins appears to be the most recent committer :wave: and appears to have actually done some CI work recently

**Comment by deivid-rodriguez** [comment]
I updated my pull request to migrate CI to Github Actions. It seems all green!
